ADTucsen
========

An https://github.com/areaDetector[areaDetector] driver for cameras from https://www.tucsen.com[Tucsen], which is also an OEM provider. e.g. https://www.axis-photon.com[Axis Photonique] soft x-ray cameras are customised Tucsen products. This driver is written with the Tucsen SDK.


System requirements
-------------------

* On Linux add a udev rule for USB interface cameras, `/etc/udev/rules.d/99-tucsen.rules`
[source]
SUBSYSTEM=="usb",ACTION=="add",ATTR{idVendor}=="5453",MODE="0666"


IOC startup script
------------------

[source]
#- Prefix for areaDetector records
epicsEnvSet("PREFIX", "SATES30-RIXS-CAM01:")
#- The port name for the detector
epicsEnvSet("PORT", "TC1")
#- The maximim image width; used to set the maximum size for this driver
#- and for row profiles in the NDPluginStats plugin
epicsEnvSet("XSIZE",  "2048")
#- The maximim image height; used to set the maximum size for this driver
#- and for column profiles in the NDPluginStats plugin
epicsEnvSet("YSIZE",  "2048")
#- The waveform is large enough for 2048x2048 pixels of short type.
epicsEnvSet("NELEMENTS", "4194304")
epicsEnvSet("TYPE", "Int16")
epicsEnvSet("FTVL", "SHORT")
#- Load and configure the driver
require "ADTucsen"

Control panels
--------------

[source,bash]
$ caqtdm -x -macro P=SATES30-RIXS-CAM01:,R=cam1: ADTucsen.ui
